### PR TITLE
Fix consecutive substractions

### LINKED ISSUE #24: v2 regression: consecutive substractions
http://requirebin.com/?gist=d519007759f777a3b9fb7c52834389e4

```
reduceCSSCalc("calc(100% - 120px - 60px)") === "calc(100% - 60px)"
```

```
reduceCSSCalc("calc(100% - 10px - 20px)" === "calc(100% - -10px)"
```

### PR DESCRIPTION
**Pull request by andyjansson**
Fixes #24

### CODE REVIEW

File: src/lib/reducer.js [hunk 1]
```diff
@@ -115,12 +115,12 @@ function reduceAddSubExpression(node, precision) {
     // (something + value) + value => something + (value + value)
     // (something - value) + value => something - (value + value)
```
Comment (sylvainpolletvillard) [inline src/lib/reducer.js]: @andyjansson by the way this is also false, it should be:
(something - valueA) + valueB => something - (valueA - valueB)

Comment (andyjansson) [reply src/lib/reducer.js]: I know. I'm fixing that now.

**Comment by ben-eb** [comment]
Thanks! 👍
